http:
  host: "0.0.0.0"
  port: "8082"
  
sapi:
  host: "customer-sapi-v1.us-e2.cloudhub.io"
  port: ""
  path:
    customers: "/api/customers"
    customerStatus: "/api/customers/status"
    
cron:
  freq: "0 0/30 * 1/1 * ? *"
  
autodiscoveryId: "17708562"
        
        
       
        